### PR TITLE
Added course description to course details page

### LINKED ISSUE #1: FEATURE: Add course description to course details page
### Have you updated the title?

- [x] I have updated the issue's title.

### As a...

User

### I can...

View a course's details

### So that...

I can know the course description

### Discussion

On the course details page, currently we only see information that is available from the course search: lecture days, times, professor, location, enrollment, etc. I would like to be able to view the course description from this page, so that I don't have to leave this search page to use the "Course Descriptions" search.

Something like this (obviously nicer-looking than this):
Your paragraph text

### Acceptance Criteria

- [x] On a course details page, there should be a text box containing the course description
- [x] This should access the course description returned from the backend's basic search (same as the Course Descriptions search)

### Implementation Todos

Frontend:
- [x] Add a component which takes a course and displays the course description
- [x] Add this component to the CourseDetailsIndexPage
- [x] Add an API call to the CourseDetailsIndexPage which calls the same API as the Course Descriptions search to get the course description

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by winzuo**
Added a component that takes a course and displays the course description.
Added this component to the CourseDetailsIndexPage.
A course details page should contain a text box with the course description.

All tests pass. 

New Course Details Page

Here's a link to an example on dokku. 
https://proj-winzuo-dev.dokku-05.cs.ucsb.edu/coursedetails/20221/53025

Screen Shot 2024-02-28 at 10 01 22 AM

### CODE REVIEW

**Review by tallyhawley — DISMISSED** [review]
Please include a link to your Dokku deployment showing these changes

**Comment by tallyhawley** [comment]
I can't access your Dokku deployment because it seems that you haven't set up HTTPS for your app.

**Comment by winzuo** [comment]
'Tis fixed.

**Comment by winzuo** [comment]
> I can't access your Dokku deployment because it seems that you haven't set up HTTPS for your app.

'Tis fixed.

**Review by ChrisWoolson — DISMISSED** [review]
LGTM!

**Review by JieTiao — APPROVED** [review]
LGTM

**Review by tallyhawley — APPROVED** [review]
LGTM!

**Pull request merged**
